# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.cache/wt [current_project]
set_property parent.project_path D:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:0.9 [current_project]
add_files D:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.srcs/sources_1/bd/design_gpio_led/design_gpio_led.bd
set_property used_in_implementation false [get_files -all d:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_processing_system7_0_0/design_gpio_led_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_rst_processing_system7_0_100M_1/design_gpio_led_rst_processing_system7_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_rst_processing_system7_0_100M_1/design_gpio_led_rst_processing_system7_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_rst_processing_system7_0_100M_1/design_gpio_led_rst_processing_system7_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_auto_pc_0/design_gpio_led_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.srcs/sources_1/bd/design_gpio_led/design_gpio_led_ooc.xdc]
set_property is_locked true [get_files D:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.srcs/sources_1/bd/design_gpio_led/design_gpio_led.bd]

read_verilog -library xil_defaultlib D:/Desktop/LED_Blinking_on_ZedBoard/zynq_Gpio.srcs/sources_1/bd/design_gpio_led/hdl/design_gpio_led_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_gpio_led_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef design_gpio_led_wrapper.dcp
catch { report_utilization -file design_gpio_led_wrapper_utilization_synth.rpt -pb design_gpio_led_wrapper_utilization_synth.pb }
